import Head from 'next/head'
import React from "react";

export default function Home() {
  return (
    <div className="py-4 px-2 min-h-screen">
      <Head>
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-center my-6 font-bold text-2xl">Welcome to next.js typescript and tailwindcss template!</h1>
        <div className="flex justify-center items-center flex-wrap my-4 mx-auto max-w-3xl">
            <Card
                title="Learn about Next.js"
                url="https://nextjs.org/docs"
                text="Check out the Next.js Docs"
            />
            <Card
                title="Learn about React"
                url="https://reactjs.org/docs/getting-started.html"
                text="Check out the React Docs"
            />
            <Card
                title="Learn about Typescript"
                url="https://www.staging-typescript.org/docs/"
                text="Check out the Typescript Docs"
            />
            <Card
            title="Learn about Tailwindcss"
            url="https://tailwindcss.com/docs"
            text="Check out the Tailwindcss docs"
            />
        </div>
      </main>
    </div>
  )
}

interface CardProps {
  url:string,
  title:string,
  text:string
}

const Card : React.FC<CardProps> = ({url, title, text })=>{
  return (
      <div className="m-4 w-1/2 border border-black rounded-2xl hover:border-blue-500 hover:text-blue-500">
        <a href={url} className="block p-4">
          <h2 className="text-xl font-bold text-black font-bold mb-4">{title} &rarr;</h2>
          <p className="text-lg font-medium text-black">{text}</p>
        </a>
      </div>
  )
}

